//////////////////////////////LOCALHOST USER////////////////////////////////

GET http://localhost:8080/users HTTP/1.1

###ID
GET http://localhost:8080/users/63e483747575c19c5fa0108d HTTP/1.1
###
GET http://localhost:8080/users/63e483ab7575c19c5fa01091 HTTP/1.1

###Post
POST http://localhost:8080/users HTTP/1.1
Content-Type: application/json

{
    "firstName": "Ariel", 
    "lastName": "Rojas", 
    "email": "test@test.com", 
    "birthday": "10/20/1990",
    "password": "admin",
    "phone": 351876,
    "address": "205 N 500 W"
}

###Post
PUT http://localhost:8080/users/63e483ab7575c19c5fa01091 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Ariel", 
    "lastName": "Rojas", 
    "email": "test1@test.com", 
    "birthday": "10/20/1990",
    "password": "password",
    "phone": 351876,
    "address": "205 N 500 W"
}

###DELETE
DELETE http://localhost:8080/users/63e483ab7575c19c5fa01091 HTTP/1.1

//////////////////////////////RENDER USER////////////////////////////////

###get
GET https://cse341-personal-z0hp.onrender.com/users

###ID
GET https://cse341-personal-z0hp.onrender.com/users/63df1a5fa1246b891f2a79c1

###POST
POST https://cse341-personal-z0hp.onrender.com/users HTTP/1.1
Content-Type: application/json

{
    "firstName": "Ariel", 
    "lastName": "Rojas", 
    "email": "test@test.com", 
    "birthday": "10/20/1990",
    "password": "admin",
    "phone": 351876,
    "address": "205 N 500 W"
}

###DELETE
DELETE https://cse341-personal-z0hp.onrender.com/users/63df33ab86b8d8cde0b23320 HTTP/1.1


//////////////////////////////LOCALHOST TICKETS////////////////////////////////

###
GET http://localhost:8080/tickets HTTP/1.1

###ID
GET http://localhost:8080/tickets/63df3f67f4aecc1900fc07ff HTTP/1.1

###Post
POST http://localhost:8080/tickets HTTP/1.1
Content-Type: application/json

{
    "origin": "Japan", 
    "destination": "Chile", 
    "departure": "10/21/2023", 
    "return": "10/31/2023"
}

###Put
PUT http://localhost:8080/tickets/63e6e109adb0d2c4fd018512 HTTP/1.1
Content-Type: application/json

{
    "origin": "Germany", 
    "destination": "Chile", 
    "departure": "10/21/2023", 
    "return": "10/31/2023"
}

###DELETE
DELETE http://localhost:8080/tickets/63df3acb037f741e4ece5732

//////////////////////////////RENDER TICKETS////////////////////////////////

###
GET https://cse341-personal-z0hp.onrender.com/tickets HTTP/1.1

###ID
GET https://cse341-personal-z0hp.onrender.com/tickets/63df25e2a07cd0e0af7e0a17 HTTP/1.1

###Post
POST https://cse341-personal-z0hp.onrender.com/tickets HTTP/1.1
Content-Type: application/json

{
    "origin": "Japan", 
    "destination": "Chile", 
    "departure": "10/21/2023", 
    "return": "10/31/2023"
}

###DELETE
DELETE https://cse341-personal-z0hp.onrender.com/tickets/63df373d037f741e4ece5715
