GET http://localhost:3000/users HTTP/1.1

###ID
GET http://localhost:3000/users/63db5be6834d15ceff3e80c6 HTTP/1.1

###Post
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "firstName": "Ariel", 
    "lastName": "Rojas", 
    "email": "ar@test.com", 
    "birthday": "10/20/1990",
    "password": "admin",
    "phone": 351876,
    "address": "205 N 500 W"
}

//TICKETS

###
GET http://localhost:3000/tickets HTTP/1.1

###ID
GET http://localhost:3000/tickets/63defb9d19fb5b2f9394f122 HTTP/1.1

###Post
POST http://localhost:3000/tickets HTTP/1.1
Content-Type: application/json

{
    "origin": "USA", 
    "destination": "Chile", 
    "departure": "10/21/2023", 
    "return": "10/31/2023"
}

